name: Run Google Test cases
author: dennuguyen

inputs:
  test_file:
    description: Test file path
    required: true
    type: string

runs:
  using: composite
  steps:
  - name: Setting up Python environment
    uses: actions/setup-python@v6
    with:
      python-version: 3.13
      cache: pip
  - run: pip install -r ./.github/actions/run-gtest/requirements.txt
  - name: Discover gtest cases
    shell: bash
    run: python3 ./.github/actions/run-gtest/discover_tests.py ${{ inputs.test_file }}
  # - name: Run test executable
  #   shell: bash
  #   run: ${{ inputs.executable }} --gtest_filter=${{ testcase_id }}