name: Run Google Test cases
author: dennuguyen

inputs:
  target:
    description: Name of test file without file extension
    required: true
    type: string

outputs:
  result:
    description: Test results
    value: ${{ steps.run-tests.outputs.result }}

runs:
  using: composite
  steps:
  - name: Build tests
    shell: bash
    run: cmake --build build --target ${{ inputs.target }}
  - name: Run tests
    id: run-tests
    shell: bash
    run: |
      TEST_FILE="${{ inputs.target }}.cpp"
      TEST_EXEC="build/${{ inputs.target }}"
      DISCOVERED_FILE=$(mktemp)
      RESULT_FILE="${{ inputs.target }}.result.json"
      REPORT_FILE="${{ inputs.target }}.report.json"

      python3 ./.github/actions/run-gtest/discover_tests.py $TEST_FILE $DISCOVERED_FILE > /dev/null
      python3 ./.github/actions/run-gtest/run_tests.py $TEST_EXEC $DISCOVERED_FILE $RESULT_FILE > /dev/null

      echo "result=$(cat $RESULT_FILE)" >> $GITHUB_OUTPUT