name: Run Google Test cases
author: dennuguyen

inputs:
  target:
    description: Name of test file without file extension
    required: true
    type: string

outputs:
  result:
    description: Test results
    value: ${{ steps.run-test.outputs.result }}

runs:
  using: composite
  steps:
  - name: Build tests
    shell: bash
    run: cmake --build build --target ${{ inputs.target }}
  - name: Run tests
    shell: bash
    run: |
      TEST_FILE="${{ inputs.target }}.cpp"
      TEST_EXEC="build/${{ inputs.target }}"
      DISCOVERED_FILE=$(mktemp)
      RESULT_FILE=$(mktemp)

      python3 ./.github/actions/run-gtest/discover_tests.py $TEST_FILE $DISCOVERED_FILE > /dev/null
      python3 ./.github/actions/run-gtest/run_tests.py $TEST_EXEC $DISCOVERED_FILE $RESULT_FILE > /dev/null

      echo "result=$RESULT_FILE" >> $GITHUB_OUTPUT