name: Copy files using map
description: |
  Copy files according to a mapping. Each mapping line is 'source: target' (paths relative to GITHUB_WORKSPACE).
author: dennuguyen

inputs:
  mapping:
    description: |
      Multiline mapping where each non-empty line is "source: target". Paths are relative to the repository workspace. For example: path_to_file_replacing: path_to_file_to_replace
    required: true

runs:
  using: composite
  steps:
  - name: Copy mapped files
    shell: python
    run: |
      import os
      import shutil
      import sys

      mapping = " ${{ inputs.mapping }} "
      if not mapping.strip():
        print("No mapping lines provided. Nothing to copy.")
        exit(0)

      for line in mapping.splitlines():
        if ":" not in line:
          print(f"'{line}' is missing ':'", file=sys.stderr)
          exit(1)

        src, dst = map(str.strip, line.split(":", 1))
        if not os.path.exists(src):
          print(f"'{line}' has no existing source path", file=sys.stderr)
          exit(1)
        if not dst:
          print(f"'{line}' is missing destination", file=sys.stderr)
          exit(1)

        if dst.endswith(os.path.sep):
          os.makedirs(os.path.dirname(dst), exist_ok=True)

        if os.path.isdir(src):
          print(f"Copying directory {src} -> {dst}", file=sys.stderr)
          shutil.copytree(src, dst, dirs_exist_ok=True)
        else:
          print(f"Copying file {src} -> {dst}", file=sys.stderr)
          shutil.copy2(src, dst)